import { basename, relative, resolve } from "node:path";

import { applyFilePlan, type FilePlanItem } from "../lib/file-plan";
import { toKebabCase } from "../lib/naming";
import type { CliResult } from "../types/cli";

interface InitOptions {
  targetPath: string;
  dryRun: boolean;
  force: boolean;
}

function parseInitArgs(args: string[]): { options?: InitOptions; error?: string } {
  let targetPath = ".";
  let targetPathProvided = false;
  let dryRun = false;
  let force = false;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === "--dry-run") {
      dryRun = true;
      continue;
    }

    if (arg === "--force") {
      force = true;
      continue;
    }

    if (arg.startsWith("--")) {
      return { error: `Unknown option for init: ${arg}` };
    }

    if (targetPathProvided) {
      return {
        error: `Too many positional arguments for init. Received extra value: ${arg}`
      };
    }

    targetPath = arg;
    targetPathProvided = true;
  }

  return {
    options: {
      targetPath,
      dryRun,
      force
    }
  };
}

function buildInitPlan(projectName: string, rootPath: string): FilePlanItem[] {
  const files: Record<string, string> = {
    ".gitignore": ["node_modules/", "dist/", "coverage/", "*.tsbuildinfo", ".DS_Store", ""].join(
      "\n"
    ),
    ".prettierignore": ["dist", "node_modules", "coverage", ""].join("\n"),
    ".prettierrc.json": JSON.stringify(
      {
        semi: true,
        singleQuote: false,
        trailingComma: "none",
        printWidth: 100
      },
      null,
      2
    ),
    "eslint.config.mjs": [
      'import js from "@eslint/js";',
      'import eslintConfigPrettier from "eslint-config-prettier";',
      'import globals from "globals";',
      'import tseslint from "typescript-eslint";',
      "",
      "export default tseslint.config(",
      "  {",
      '    ignores: ["dist/**", "node_modules/**", "coverage/**"]',
      "  },",
      "  js.configs.recommended,",
      "  ...tseslint.configs.recommended,",
      "  eslintConfigPrettier,",
      "  {",
      '    files: ["**/*.ts"],',
      "    languageOptions: {",
      "      globals: {",
      "        ...globals.node",
      "      }",
      "    }",
      "  }",
      ");",
      ""
    ].join("\n"),
    "package.json": JSON.stringify(
      {
        name: projectName,
        version: "0.1.0",
        private: true,
        description: "Generated by Agent Alpha starter kit",
        main: "dist/index.js",
        types: "dist/index.d.ts",
        bin: {
          [projectName]: "dist/cli.js"
        },
        scripts: {
          dev: "tsx src/cli.ts",
          lint: "eslint .",
          format: "prettier . --write",
          "format:check": "prettier . --check",
          build: "tsc -p tsconfig.json",
          typecheck: "tsc --noEmit -p tsconfig.json",
          test: "vitest run",
          start: "node dist/cli.js"
        },
        packageManager: "pnpm@10.30.2",
        engines: {
          node: ">=22.0.0"
        },
        devDependencies: {
          "@eslint/js": "^9.39.3",
          "@types/node": "^22.19.11",
          eslint: "^9.39.3",
          "eslint-config-prettier": "^10.1.8",
          globals: "^16.5.0",
          prettier: "^3.8.1",
          tsx: "^4.21.0",
          typescript: "^5.9.3",
          "typescript-eslint": "^8.56.1",
          vitest: "^3.2.4"
        }
      },
      null,
      2
    ),
    "tsconfig.json": [
      "{",
      '  "compilerOptions": {',
      '    "target": "ES2022",',
      '    "module": "CommonJS",',
      '    "moduleResolution": "Node",',
      '    "strict": true,',
      '    "esModuleInterop": true,',
      '    "forceConsistentCasingInFileNames": true,',
      '    "skipLibCheck": true,',
      '    "declaration": true,',
      '    "outDir": "dist",',
      '    "rootDir": "src",',
      '    "types": ["node", "vitest/globals"]',
      "  },",
      '  "include": ["src/**/*.ts", "tests/**/*.ts"],',
      '  "exclude": ["dist", "node_modules"]',
      "}",
      ""
    ].join("\n"),
    "README.md": [
      `# ${projectName}`,
      "",
      "Generated by Agent Alpha CLI starter kit.",
      "",
      "## Commands",
      "",
      "- Add command files under `src/commands/`.",
      "- Register commands in `src/commands/registry.ts` (auto-managed by Agent Alpha generator).",
      "",
      "## Quickstart",
      "",
      "```bash",
      "corepack pnpm install",
      "corepack pnpm lint",
      "corepack pnpm format:check",
      "corepack pnpm typecheck",
      "corepack pnpm test",
      "corepack pnpm build",
      "```",
      ""
    ].join("\n"),
    "src/cli.ts": [
      "#!/usr/bin/env node",
      "",
      'import { runCli } from "./index";',
      "",
      "void runCli(process.argv.slice(2)).then((exitCode) => {",
      "  process.exitCode = exitCode;",
      "});",
      ""
    ].join("\n"),
    "src/index.ts": [
      'import { commandRegistry, findCommand } from "./commands/registry";',
      "",
      "function buildHelpText(): string {",
      "  const commandLines = commandRegistry.length",
      "    ? commandRegistry.map((command) => `  ${command.name}  ${command.summary}`)",
      '    : ["  (no commands registered yet)"];',
      "",
      "  return [",
      `    "${projectName}",`,
      '    "",',
      '    "Usage: starter <command> [options]",',
      '    "",',
      '    "Global options:",',
      '    "  -h, --help       Show help",',
      '    "  -v, --version    Show version",',
      '    "",',
      '    "Commands:",',
      "    ...commandLines",
      '  ].join("\\\\n");',
      "}",
      "",
      "export async function runCli(argv: string[]): Promise<number> {",
      '  if (!argv.length || argv[0] === "--help" || argv[0] === "-h") {',
      "    process.stdout.write(`${buildHelpText()}\\\\n`);",
      "    return 0;",
      "  }",
      "",
      '  if (argv[0] === "--version" || argv[0] === "-v") {',
      '    process.stdout.write("0.1.0\\n");',
      "    return 0;",
      "  }",
      "",
      "  const command = findCommand(argv[0]);",
      "  if (!command) {",
      "    process.stderr.write(`Unknown command: ${argv[0]}\\\\n`);",
      "    return 1;",
      "  }",
      "",
      "  const result = await command.run(argv.slice(1), process.cwd());",
      "  if (result.message) {",
      '    const line = result.message.endsWith("\\\\n") ? result.message : `${result.message}\\\\n`;',
      '    if (result.stream === "stderr") {',
      "      process.stderr.write(line);",
      "    } else {",
      "      process.stdout.write(line);",
      "    }",
      "  }",
      "",
      "  return result.exitCode;",
      "}",
      ""
    ].join("\n"),
    "src/commands/registry.ts": [
      'import type { CliResult } from "../types/cli";',
      "// AUTO-GENERATED IMPORTS START",
      "// AUTO-GENERATED IMPORTS END",
      "",
      "export interface RegisteredCommand {",
      "  name: string;",
      "  summary: string;",
      "  usage: string;",
      "  run: (args: string[], cwd: string) => Promise<CliResult>;",
      "}",
      "",
      "const generatedCommands: RegisteredCommand[] = [",
      "  // AUTO-GENERATED ENTRIES START",
      "  // AUTO-GENERATED ENTRIES END",
      "];",
      "",
      "export const commandRegistry: RegisteredCommand[] = [...generatedCommands];",
      "",
      "export function findCommand(name: string): RegisteredCommand | undefined {",
      "  return commandRegistry.find((command) => command.name === name);",
      "}",
      ""
    ].join("\n"),
    "src/types/cli.ts": [
      'export type CliStream = "stdout" | "stderr";',
      "",
      "export interface CliResult {",
      "  exitCode: number;",
      "  stream?: CliStream;",
      "  message?: string;",
      "}",
      ""
    ].join("\n"),
    "tests/cli.smoke.test.ts": [
      'import { describe, expect, it } from "vitest";',
      "",
      'import { runCli } from "../src/index";',
      "",
      'describe("runCli", () => {',
      '  it("returns success for --help", async () => {',
      '    await expect(runCli(["--help"])).resolves.toBe(0);',
      "  });",
      "});",
      ""
    ].join("\n"),
    ".github/workflows/ci.yml": [
      "name: CI",
      "",
      "on:",
      "  push:",
      "    branches:",
      "      - main",
      "  pull_request:",
      "",
      "jobs:",
      "  validate:",
      "    runs-on: ubuntu-latest",
      "",
      "    steps:",
      "      - name: Checkout",
      "        uses: actions/checkout@v4",
      "",
      "      - name: Setup pnpm",
      "        uses: pnpm/action-setup@v4",
      "        with:",
      "          version: 10.30.2",
      "",
      "      - name: Setup Node",
      "        uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 22",
      "          cache: pnpm",
      "",
      "      - name: Install dependencies",
      "        run: pnpm install --frozen-lockfile",
      "",
      "      - name: Lint",
      "        run: pnpm lint",
      "",
      "      - name: Format check",
      "        run: pnpm format:check",
      "",
      "      - name: Typecheck",
      "        run: pnpm typecheck",
      "",
      "      - name: Test",
      "        run: pnpm test",
      "",
      "      - name: Build",
      "        run: pnpm build",
      ""
    ].join("\n"),
    "tasks/todo.md": [
      "# Task Todo",
      "",
      "## Plan",
      "- [ ] Add first production command.",
      "- [ ] Add tests for first command.",
      "",
      "## Progress Notes",
      "- Pending.",
      "",
      "## Review / Results",
      "- Pending.",
      ""
    ].join("\n"),
    "tasks/lessons.md": [
      "# Lessons Log",
      "",
      "## Template",
      "- Date/Session:",
      "- Correction Pattern:",
      "- Root Cause:",
      "- Prevention Rule:",
      "- Validation Note:",
      ""
    ].join("\n"),
    "docs/architecture.md": [
      "# Architecture",
      "",
      "## Runtime",
      "- Node + TypeScript CLI",
      "- GitHub Actions CI",
      "- Deterministic project layout",
      ""
    ].join("\n")
  };

  return Object.entries(files).map(([path, content]) => ({
    path: resolve(rootPath, path),
    content
  }));
}

function summarizeCreatedPaths(created: string[], cwd: string): string {
  if (created.length === 0) {
    return "(none)";
  }

  return created.map((path) => `- ${relative(cwd, path) || path}`).join("\n");
}

export async function runInitCommand(args: string[], cwd: string): Promise<CliResult> {
  const parsed = parseInitArgs(args);
  if (parsed.error) {
    return {
      exitCode: 1,
      stream: "stderr",
      message: `${parsed.error}\nUsage: agent-alpha init [target-path] [--dry-run] [--force]`
    };
  }

  const options = parsed.options as InitOptions;
  const rootPath = resolve(cwd, options.targetPath);
  const projectName = toKebabCase(basename(rootPath));
  const plan = buildInitPlan(projectName, rootPath);
  const applied = await applyFilePlan(plan, {
    dryRun: options.dryRun,
    force: options.force
  });

  if (applied.collisions.length > 0) {
    return {
      exitCode: 1,
      stream: "stderr",
      message: [
        "Init aborted. The following files already exist:",
        ...applied.collisions.map((path) => `- ${relative(cwd, path) || path}`),
        "Re-run with --force to overwrite existing files."
      ].join("\n")
    };
  }

  if (options.dryRun) {
    return {
      exitCode: 0,
      stream: "stdout",
      message: [
        `Dry run: ${applied.created.length} files would be created in ${rootPath}.`,
        summarizeCreatedPaths(applied.created, cwd)
      ].join("\n")
    };
  }

  return {
    exitCode: 0,
    stream: "stdout",
    message: [
      `Initialized starter project in ${rootPath}.`,
      `Created ${applied.created.length} files.`,
      "",
      "Next steps:",
      `1. cd ${relative(cwd, rootPath) || "."}`,
      "2. corepack pnpm install",
      "3. corepack pnpm typecheck",
      "4. corepack pnpm test"
    ].join("\n")
  };
}
